### ISSUE TITLE
After ldap

### ISSUE THREAD

**Issue by dfquaresma** [Guardians-DSC/iarl#10]
After a successful authentication via ldap, what will we do with the login and password of the client? Should  we save it in some place to use later?

**Comment by danielrcoura** [comment]
Currently, the system saves in a session variable for login in laboratories.

**Comment by dfquaresma** [comment]
@danielrcoura it sounds good to me. Did you already updated it on master?

**Comment by MatheusCMelo** [comment]
Shouldn't we use stateless authentication rather than sessions?

**Comment by danielrcoura** [comment]
@dfquaresma Yes, I did.

**Comment by dfquaresma** [comment]
@MatheusCMelo same ask made to @kaiokassiano at #9 . What is the advantages of use stateless authentication rather than sessions?

**Comment by dfquaresma** [comment]
@danielrcoura I thought you was going to make a PR yet, since there is a branch called directory-list.

**Comment by MatheusCMelo** [comment]
Instead of storaging the user session in backend, when a user logs in, the server generates a token, which is valid for a certain amount of time without being used or until the user logs out. This token is storaged in the client, keeping the application scalable.

**Comment by dfquaresma** [comment]
Interesting! Since master's branch was update following another way, I believe that change it could be a future feature. What do you guys think? So until there this issue can stay opened to remind us about it.

**Comment by danielrcoura** [comment]
@MatheusCMelo I generated the token, I used [this site](https://code.tutsplus.com/tutorials/token-based-authentication-with-angularjs-nodejs--cms-22543) as a guide. How do I store the user and password for ssh operations? Should it be stored on the client side?

**Comment by MatheusCMelo** [comment]
@danielrcoura I think the best option is to store user and password along with the token in a db but it may be a good point to be discussed.

**Comment by danielrcoura** [comment]
As the system will not need to use ssh, it is no longer necessary to save the password, just the username to access the user's folder. Given the demand and simplicity of the API, I think it is better to use session instead of token. The username will be saved in RAM, it will not be expensive since with 1MB it is possible to store 10^6 characters.
