### ISSUE TITLE
Directory listing

### ISSUE THREAD

**Issue by dfquaresma** [Guardians-DSC/iarl#11]
How will we list the directories of an user? The real client of our back-end application is our front-end. How will be the json of directory listing returned to the front?

**Comment by danielrcoura** [comment]
The command sftp.list(<directory_path>) returns a list of directories where each element is the type:
```
{
    "type": "d",
    "name": "example",
    "size": 4096,
    "modifyTime": 1513888761000,
    "accessTime": 1513888897000,
    "rights": {
        "user": "rwx",
        "group": "rx",
        "other": "rx"
    },
    "owner": 20369,
    "group": 100
}
```

**Comment by dfquaresma** [comment]
So you have done it already. Great! When you make a pull request please tag that issue. Thanks
