### ISSUE TITLE
Work with issues

### ISSUE THREAD

**Issue by dfquaresma** [Guardians-DSC/iarl#8]
I think we could start opening issues and resolving them with our PRs. What do you guys think?

**Comment by MatheusCMelo** [comment]
gr8 m8

**Comment by dfquaresma** [comment]
It's too simples associate a PR with a issue. Just use a "#x" in discription of your PR. The "x" is the number associated to the issue you want solve.

**Comment by dfquaresma** [comment]
I believe we are already doing it now, so i'm closing this issue.
