### ISSUE TITLE
Invalid jsons

### ISSUE THREAD

**Issue by dfquaresma** [Guardians-DSC/iarl#9]
What should we do when our application receives an invalid json?

**Comment by MatheusCMelo** [comment]
Return 400 - Bad Request and maybe a json indicating the error

**Comment by dfquaresma** [comment]
It sounds good to me. I believe @danielrcoura is already doing that, right?

**Comment by kaiokassiano** [comment]
I'd use 412 instead of 400.

**Comment by dfquaresma** [comment]
@kaiokassiano why 412 or 422 is better than 400?

**Comment by dfquaresma** [comment]
@kaiokassiano what is the advantages of use 412 or 422 upon 400?

**Comment by kaiokassiano** [comment]
@dfquaresma those two can provide a better explanation than "bad request".

The definition of 400 (Bad Request) in [this link](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) says: 
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

We can consider use 422 (Unprocessable Entity), which states:
> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415 (Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions.

You can take a further look [here](https://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm).

**Comment by dfquaresma** [comment]
@kaiokassiano thanks! I agree with you. I think we can go with 422.

**Comment by MatheusCMelo** [comment]
So be it.

**Comment by dfquaresma** [comment]
Already satisfied.
